# numpy

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5,6])

In [3]:
a

array([1, 2, 3, 4, 5, 6])

In [6]:
a.dtype


dtype('int32')

In [7]:
a.shape


(6,)

In [8]:
a.ndim


1

In [9]:

a.size


6

In [10]:
a[1]

2

In [12]:
b=np.array([[1,2,3],[4,5,6]])

In [13]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
b.dtype

dtype('int32')

In [15]:
b.shape

(2, 3)

In [16]:
b.ndim

2

In [17]:
a.size

6

In [18]:
a[0]

1

In [19]:
b[1]

array([4, 5, 6])

In [20]:
c=np.array([[[1,2,3]]])

In [21]:
c

array([[[1, 2, 3]]])

In [22]:
c.dtype

dtype('int32')

In [23]:
c.shape

(1, 1, 3)

In [24]:
c.shape

(1, 1, 3)

In [25]:
c.size


3

In [27]:
b=np.array([[1,2,3],[4,5,6]], dtype=float )



In [28]:
b

array([[1., 2., 3.],
       [4., 5., 6.]])

In [29]:
b.dtype

dtype('float64')

## fill arrays

In [38]:
d=np.full((1,5,4),7)

In [39]:
d

array([[[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]])

In [40]:
d.ndim

3

In [43]:
e=np.zeros((3,3))

In [44]:
e

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [45]:
f=np.ones((3,3))

In [46]:
f

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [56]:
g=np.empty((3,3))

In [57]:
g

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [58]:
h=np.random.random((2,2))

In [59]:
h

array([[0.08690047, 0.5437893 ],
       [0.12140878, 0.80812143]])

In [61]:
i=np.arange(1,50,2)

In [62]:
i

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [63]:
j=np.linspace(1,50,2)

In [64]:
j

array([ 1., 50.])

In [65]:
k=np.linspace(1,50,20)

In [66]:
k

array([ 1.        ,  3.57894737,  6.15789474,  8.73684211, 11.31578947,
       13.89473684, 16.47368421, 19.05263158, 21.63157895, 24.21052632,
       26.78947368, 29.36842105, 31.94736842, 34.52631579, 37.10526316,
       39.68421053, 42.26315789, 44.84210526, 47.42105263, 50.        ])

In [68]:
a

array([1, 2, 3, 4, 5, 6])

In [67]:
print(np.exp(a))
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))
print(np.log(a))
print(np.sqrt(a))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
